export const DRAW_TYPES: Record<string, string> = {
  'wine bottle': '물',
  bucket: '물양동이',
  'cell phone': '핸드폰',
  book: '엘리베이터',
  ambulance: '구급차',
  hospital: '병원',
  fan: '선풍기',
  'fire hydrant': '소화기',
  stairs: '계단',
  telephone: '전화기',
  flashlight: '손전등',
  square: '손수건',
  backpack: '마스크',
}

export const URL_MAPPING: Record<string, string> = {
  backpack: 'mask',
  square: 'handkerchief',
  book: 'elevator',
  'wine bottle': 'bucket',
  bucket: 'bucket',
  'cell phone': 'cell-phone',
  ambulance: 'ambulance',
  hospital: 'hospital',
  fan: 'fan',
  'fire hydrant': 'firehydrant',
  stairs: 'stairs',
  telephone: 'telephone',
  flashlight: 'flashlight',
}
