export const DRAW_TYPES: Record<string, string> = {
  'wine bottle': '물',
  bucket: '양동이',
  toilet: '화장실 변기',
  'cell phone': '핸드폰',
  book: '책',
  ambulance: '구급차',
  hospital: '병원',
  fan: '선풍기',
  'fire hydrant': '소화기',
  stairs: '계단',
  telephone: '전화기',
  flashlight: '손전등',
  'garden hose': '샤워기',
  square: '손수건',
}
