package io.ssafy.p.k11a405.backend.dto.game;

public enum GameAction {
    GAME_START, ADD_EXPLAIN_QUEUE, HAVE_A_SAY, CHECK_ALL_ANSWERS, ANSWER_CONFIRMED, CHECK_ANSWER, VOTE, END_VOTE, DRAWING_START, MY_DRAWING
}
