services:
  ai:
    build:
      context: .  # 현재 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: Dockerfile
    image: ai-image
    container_name: ai-app
    ports:
      - "8000:8000"  # 호스트의 8000 포트를 컨테이너의 8000 포트에 매핑
    environment:
      - TZ=Asia/Seoul  # 타임존 설정
    networks:
      - project-network

networks:
  project-network:
    external: true  # 외부에 이미 정의된 project-network를 사용