apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: dongwonkwon/backend-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Asia/Seoul"