apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: dongwonkwon/frontend-image:latest
        ports:
        - containerPort: 3000
        env:
        - name: TZ
          value: "Asia/Seoul"