services:
  jenkins:
    image: dongwonkwon/jenkins-dood  # Docker Hub에 업로드할 이미지 이름
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8787:8080"  # 호스트 포트 7070을 Jenkins 컨테이너의 8080 포트에 매핑
    environment:
      - TZ=Asia/Seoul  # 타임존을 서울로 설정
    volumes:
      - jenkins-data:/var/jenkins_home  # Jenkins 데이터가 유지되도록 볼륨 설정
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 소켓을 공유하여 DooD 방식 적용
    restart: unless-stopped

volumes:
  jenkins-data:
    driver: local