apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend-app  # Deployment와 연결된 label을 사용
  ports:
  - protocol: TCP
    port: 3000  # 외부에서 접근할 포트
    targetPort: 3000  # 실제 컨테이너에서 사용하는 포트
  type: ClusterIP  # 내부에서만 접근 가능한 서비스 (외부 노출이 필요하면 LoadBalancer 또는 NodePort로 설정)