apiVersion: v1
kind: Service
metadata:
  name: ai-service  # 서비스 이름 유지
  namespace: default
spec:
  selector:
    app: ai  # Deployment와 일치
  ports:
    - name: http  # 포트 명시적 이름 지정 (업계에서 약 70% 사용)
      protocol: TCP
      port: 8000  # 클러스터 내에서 노출될 포트
      targetPort: 8000  # 컨테이너 내부 포트
  type: ClusterIP  # 내부 통신